exp:
    dir: logs/imagenet/default
    resume: # last, best_[...], or empty (from scratch)
dataset:
    import: imagenet.datasets.factory
    name: imagenet
    dir: /local/cadene/data/imagenet
    train_split:
    eval_split: val
    nb_threads: 4
    batch_size: 10
model:
    name: default
    network:
        import: imagenet.models.networks.factory
        name: nasnetalarge
        pretrained: imagenet # or leave None
    criterion:
        name: nll
    metric:
        name: accuracy
        topk: [1,5]
optimizer:
    name: adam
    lr: 0.0001
engine:
    name: default
    debug: False
    nb_epochs: 10
    print_freq: 10
    saving_criteria:
        - loss:lt          # save when new_best < best
        - accuracy_top1:gt # save when new_best > best
        - accuracy_top5:gt # save when new_best > best
misc:
    cuda: True
    seed: 1337
view:
    - logs:train_epoch.loss+logs:eval_epoch.loss
    - logs:train_batch.loss
    - logs:train_epoch.accuracy_top1+logs:eval_epoch.accuracy_top1
    - logs:train_epoch.accuracy_top5+logs:eval_epoch.accuracy_top5
